export enum ApiURLNames {
  MAIN_URL = "http://localhost:5000/api",
  URL_IMAGES = "http://localhost:5000/img/",
  URL_AUDIO = "http://localhost:5000/music/",
  LOGIN = "/login",
  REGISTRATION = "/registration",
  LOGOUT = "/logout",
  USERS = "/users",
  REFRESH_TOKEN = "/refresh",
  POST = "/post",
  POSTS = "/posts",
  POSTS_USER = "/posts/me",
  TRACKS_USER = "/tracks/me",
  TRACK = "/track",
}
